# Generated by Django 5.1 on 2024-08-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_rename_time_to_do_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='gallery/')),
                ('alt', models.CharField(default='Image Name', max_length=255)),
            ],
        ),
    ]
